spring:
  profiles:
    active: dev
server:
  port: 8401
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      register-with-eureka: true
      prefer-ip-address: true      
