spring:
  profiles:
    active:
    - dev
---
spring:
  application:
    name: microservice-config-eureka-client
  profiles:
    active: dev
server:
  port: 6001

eureka:
  instance:
    hostname=microservice-config-eureka-client:
  client:
    service-url:
      defaultZone: http://localhost:6001/eureka
      register-with-eureka: false
      prefer-ip-address: false
---
spring:
  application:
    name: microservice-config-eureka-client
  profiles:
    active: test
server:
  port: 6002

eureka:
  instance:
    hostname=microservice-config-eureka-client:
  client:
    service-url:
      defaultZone: http://localhost:6002/eureka
      register-with-eureka: false
      prefer-ip-address: false

